### ISSUE TITLE
cannot run the code

### ISSUE THREAD

**Issue by ghost** [rainyear/avgot#1]
It seems the self._ENTRY passed a NoneType. 

Traceback (most recent call last):
  File "~/Projects/crawler/src/crawling.py", line 77, in work
    results = await node.callback(await self.extract(node.url, node.re), node.parent)
AttributeError: 'NoneType' object has no attribute 'callback'

**Comment by rainyear** [comment]
@nychent which URL were you crawling?

**Comment by ghost** [comment]
Hi, douban you listed in your code. 
I just download and run, nothing changed.

**Comment by rainyear** [comment]
@nychent maybe they've already changed their sites' structures, you might need to modify the regular expressions by yourself.
